// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgcmkflhganantpqokks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnY21rZmxoZ2FuYW50cHFva2tzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDkzMzIsImV4cCI6MjA1ODY4NTMzMn0.RA_xsW_4tbwlULDFSsAnk1-upwJ_1EBB-ug7fYa68Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);